neutrons/MagnetismReflectometer

- environment.yml
Just include finddata in the `environment.yml` file
References [EWM5145](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=5145)
> add finddata dependency

- src/mr_autoreduce/reduce_REF_M.py.template
It is strongly encouraged that the reviewer runs the following tests in their local machine
because these tests are not run by the GitLab CI. It is assumed that the reviewer has the /SNS and /HFIR filesystems
remotely mounted in their machine.
```bash
cd /path/to/my/local/mr_reduction/repo/
git fetch origin merge-requests/<MERGE_REQUEST_NUMBER>/head:mr<MERGE_REQUEST_NUMBER>
git switch mr<MERGE_REQUEST_NUMBER>
conda activate <my_mr_reduction_environment>
pytest -m mount_eqsans ./tests/unit/ ./tests/integration/
```
In the above code snippet, substitute `<MERGE_REQUEST_NUMBER>` for the actual merge request number. Also substitute
`<my_mr_reduction_environment>` …
> remove unused import

- .github/pull_request_template.md
- docs/releases.rst
- environment.yml
Just updated the release-notes files with the latest pull requests
Links to IBM EWM items: [6311](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=6311)
> Update release notes

- docs/releases.rst
- src/mr_autoreduce/reduce_REF_M_run.py
- src/mr_autoreduce/reduce_REF_M_run.sh
- Links to IBM EWM items: [6326](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=6326), [5986](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=5986)
> increase timeout to prevent worker being killed

- docs/release_notes.rst
- src/mr_livereduce/polarization_analysis.py
- src/mr_reduction/data_info.py
- src/mr_reduction/mr_direct_beam_finder.py
- src/mr_reduction/mr_filter_events.py
- src/mr_reduction/mr_reduction.py
- src/mr_reduction/reflectivity_output.py
- src/mr_reduction/simple_utils.py
- src/mr_reduction/web_report.py
- tests/integration/test_mr_reduction.py
- tests/unit/mr_reduction/test_simple_utils.py
Introduction of a `SampleLogs` class to reduce boilerplate code and make the code more pythonic and understandable.
- ~updated documentation~
- ~Added integration tests~
- Links to IBM EWM items: [849](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=8489)
Just run the tests locally with one core `pytest -n 1 tests/`
> Class SampleLogs

- docs/release_notes.rst
- src/mr_reduction/reflectivity_output.py
- tests/unit/mr_reduction/test_reflectivity_output.py
The purpose of this `dataclass` is to store options that can be used to write the reflectivity file to QuickNXS format (already implemented) or ORSO format (to be implemented)
- ~updated documentation~
- ~Added integration tests~
- Links to IBM EWM items: [8489](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=8489)
Just make sure that `pytest -n 1 tests/` passes on your local repository.
> Class DirectBeamOptions

- src/mr_autoreduce/templates/reduction_options.html
- Links to IBM EWM items:
- Links to related issues or pull requests:
> vertical is better understood by the user

- .github/pull_request_template.md
- docs/release_notes.rst
- docs/user/reduce.rst
- src/mr_autoreduce/reduce_REF_M_run.py
- src/mr_reduction/mr_reduction.py
- src/mr_reduction/web_report.py
- Links to IBM EWM items: [10260](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=10260)
Start the [manual reduction](https://mr-reduction.readthedocs.io/en/pv_to_orso/user/reduce.html#manual-reduction) and accept the default values by clicking the "Submit" button.
Once button "View Report" becomes enabled, click it to view the generated HTML report, which is file `/tmp/test_43884/REF_M_REF_M_43884.html`.
Compare the size of `/tmp/test_43884/REF_M_REF_M_43884.html` with that of original report 
[REF_M_REF_M_43884_original.html.zip](https://github.com/user-attachments/files/19327758/REF_M_REF_M_4388 …
> do not plot non-finite or non-significant data

- docs/release_notes.rst
- src/mr_reduction/io_orso.py
- src/mr_reduction/mr_reduction.py
- src/mr_reduction/reflectivity_merge.py
- src/mr_reduction/scripts/nexus_to_orso.py
- tests/unit/mr_reduction/test_io_orso.py
- Links to IBM EWM items: [7274](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=7274)
> Saving all cross-sections for the combined profiles in one ORSO-formatted file

- docs/release_notes.rst
- docs/user/reduce.rst
- src/mr_autoreduce/reduce_REF_M.py.template
- src/mr_reduction/io_orso.py
- src/mr_reduction/mr_reduction.py
- src/mr_reduction/reflectivity_merge.py
- tests/integration/test_mr_reduction.py
- tests/unit/mr_reduction/test_io_orso.py
- Links to IBM EWM items: [10275](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=10278)
> Introduce ORSO-saving functionality in the autoreduction workflow

- conda.recipe/meta.yaml
- docs/release_notes.rst
- environment.yml
- src/mr_reduction/io_orso.py
- Links to IBM EWM items: [Story 10174: [Cyber][MrRED] Update mantid ver >=6.12.0](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=10174)
- Links to related issues or pull requests:
> Update mantid version to 6.12

- src/mr_reduction/settings.py
- Links to IBM EWM items: [10832](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=10832)
No test needed 
> revert to old PV names

- docs/release_notes.rst
- src/mr_reduction/filter.py
- src/mr_reduction/filter_events.py
- src/mr_reduction/mr_reduction.py
- src/mr_reduction/simple_utils.py
- tests/conftest.py
- tests/integration/test_filter_events.py
- tests/integration/test_reduce_REF_M_live_post_proc.py
- tests/unit/mr_reduction/test_filter_events.py
- Links to IBM EWM items: [10902](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=10902)
> bugfix for runs containing logs with time entries predating the start of the run

- docs/release_notes.rst
- src/mr_livereduce/livereduce.conf
- Links to IBM EWM items: [10951](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=10951)
> update livereduce.conf file

- .github/pull_request_template.md
- docs/release_notes.rst
- pyproject.toml
- src/mr_livereduce/polarization_analysis.py
- src/mr_reduction/filter_events.py
- src/mr_reduction/mr_reduction.py
- src/mr_reduction/script_output.py
- src/mr_reduction/simple_utils.py
- src/mr_reduction/types.py
- tests/integration/test_filter_events.py
- tests/integration/test_reduce_REF_M_live_post_proc.py
- tests/integration/test_simple_reduction.py
- tests/unit/mr_reduction/test_filter_events.py
…clarity and usability
- Links to IBM EWM items: [11120](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=11120)
No need to manually test, only review the source code
> Convert Mantid algorithm MRFilterCrossSections to a module of mr_reduction

- tests/integration/test_mr_reduction.py
Integration test to make sure that normalization with the direct beam run works as intended
- Links to IBM EWM items: [11096](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=11096)
No need for a manual test
> Add normalization-check test for reflectivity values in MR reduction

- src/mr_reduction/inspect_data.py
- src/mr_reduction/oncat_comm.py
Some suggested changes to #55 
Includes formatting changes from pre-commit Ruff
> Suggested changes for Jose's PR

- docs/release_notes.rst
- src/mr_reduction/data_info.py
- src/mr_reduction/inspect_data.py
- src/mr_reduction/oncat_comm.py
- Links to IBM EWM items: [1115](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=11155)
No need to manually test anything
> Refactor MRInspectData as module inspect_data

- .github/workflows/testing.yml
- docs/release_notes.rst
- environment.yml
- src/mr_reduction/data_info.py
- src/mr_reduction/inspect_data.py
- src/mr_reduction/mr_direct_beam_finder.py
- src/mr_reduction/mr_reduction.py
- tests/integration/test_mr_reduction.py
- tests/unit/mr_reduction/test_inspect_data.py
- Links to IBM EWM items: [11271](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=11271)
No manual test necessary
> Incorporate ROI3 and ROI4 to the reduction workflow

- pixi.lock
- pyproject.toml
- Links to IBM EWM items: [12508](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=12508)
> Pin mantid and add run-dependencies
